# Generated by Django 4.1.1 on 2022-09-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activites', models.CharField(blank=True, choices=[('1', 'сельское хозяйство'), ('2', 'торговля'), ('3', 'производство'), ('4', 'заготовка и переработка'), ('5', 'промышленность'), ('6', 'торговля и коммерция'), ('7', 'строительство'), ('8', 'транспорт'), ('9', 'услуги'), ('10', 'прочие')], max_length=100, null=True, verbose_name='Источник дохода')),
                ('activites_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Добавить источник дохода')),
            ],
            options={
                'verbose_name_plural': 'Сфера деятельности',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('credit_type', models.CharField(choices=[('LS', 'Лизинг'), ('CR', 'Кредит')], max_length=30, verbose_name='Тип кредита')),
                ('client_status', models.CharField(choices=[('Принят', 'Принят'), ('Отказано', 'Отказано')], max_length=30, verbose_name='Статус клиента')),
                ('credit_sum', models.CharField(max_length=30, verbose_name='Сумма кредита')),
                ('marital_status', models.CharField(choices=[('Женат/Замужем', 'Женат/Замужем'), ('Разведен', 'Разведен'), ('Вдова/Вдовец', 'Вдова/Вдовец'), ('Холост/Незамужем', 'Холост/Незамужем')], max_length=30, verbose_name='Семейное положение')),
                ('credit_history', models.FileField(blank=True, default='Кредитная история отсутствует', null=True, upload_to='client_credit_history/%Y/%m/%d', verbose_name='Кредитная история')),
                ('phone', models.CharField(default='+996', max_length=100, unique=True, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес прописки')),
                ('client_actual_address', models.CharField(default='Тот же что и по прописке', max_length=100, verbose_name='Адрес фактический')),
                ('guarantor', models.CharField(max_length=100, verbose_name='Поручитель')),
                ('income_statement', models.FileField(blank=True, null=True, upload_to='client_income_statement/%Y/%m/%d', verbose_name='Справка о доходах')),
                ('mortgaged_property', models.CharField(max_length=255, verbose_name='Залоговое имущество')),
                ('contracts', models.FileField(blank=True, null=True, upload_to='contracts_with_suppliers/%Y/%m/%d', verbose_name='Договора с подрядчиками и поставщиками')),
                ('report', models.FileField(blank=True, null=True, upload_to='reports_with_suppliers/%Y/%m/%d', verbose_name='Oтчет подрядчиков и поставщиков об оказанной услугe')),
                ('monitoring_report', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Oтчет по мониторингу')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='CreditSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО кредитного специалиста')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО залогодателя')),
                ('status', models.CharField(choices=[('Женат/Замужем', 'Женат/Замужем'), ('Разведен', 'Разведен'), ('Вдова/Вдовец', 'Вдова/Вдовец'), ('Холост/Незамужем', 'Холост/Незамужем')], max_length=30, verbose_name='Семейное положение')),
                ('credit_history', models.FileField(upload_to='credit_history/%Y/%m/%d')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес прописки')),
                ('actual_address', models.CharField(max_length=100, verbose_name='Адрес фактический')),
                ('income_statement', models.FileField(upload_to='guarantor_income_statement/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Поручитель',
                'verbose_name_plural': 'Поручители',
            },
        ),
        migrations.CreateModel(
            name='MeetConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Личные встречи',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_job_title', models.CharField(blank=True, choices=[('CreditSpecialist', 'Кредитный специалист'), ('Creditadministrator', 'Кредитный администратор')], max_length=100, null=True, verbose_name='Наименование должности')),
                ('name_job_title_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Добавить должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Залоговое имущество')),
                ('address', models.CharField(max_length=100, verbose_name='Местонахождение залога')),
                ('document', models.FileField(upload_to='document/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Залоговое имущество',
                'verbose_name_plural': 'Залоговые имущества',
            },
        ),
        migrations.CreateModel(
            name='TelephoneConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Телефонные переговоры',
            },
        ),
        migrations.CreateModel(
            name='DataKK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('credit_spec_report', models.FileField(upload_to='credit_spec/%Y/%m/%d', verbose_name='Заключение кредитного эксперта (скан):')),
                ('committee_decision', models.FileField(upload_to='decision/%Y/%m/%d', verbose_name='Решение КК (скан):')),
                ('all_contracts', models.FileField(upload_to='all_contracts/%Y/%m/%d', verbose_name='Все заключенные договора, перечень и сканы:')),
                ('scoring', models.CharField(max_length=150, verbose_name='Скоринг:')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.client')),
                ('id_spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.creditspecialist')),
            ],
            options={
                'verbose_name': 'Документ на КК',
                'verbose_name_plural': 'Документы на КК',
            },
        ),
        migrations.AddField(
            model_name='creditspecialist',
            name='job_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.occupation'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование компании')),
                ('inn', models.CharField(max_length=14, unique=True)),
                ('legal_address', models.CharField(max_length=100, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(max_length=100, verbose_name='Фактический адрес')),
                ('telephone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('okpo', models.CharField(max_length=8, unique=True)),
                ('register_number', models.CharField(max_length=30, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='company_files/%Y/%m/%d')),
                ('field_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.activity', verbose_name='Cфера деятельности')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='id_credit_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.creditspecialist'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.guarantor'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_num_parley',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.telephoneconversation'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.property'),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.client')),
                ('client_company', models.CharField(max_length=50, verbose_name='Компания клиента')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('souce_of_income', models.CharField(choices=[('1', 'сельское хозяйство'), ('2', 'торговля'), ('3', 'производство'), ('4', 'заготовка и переработка'), ('5', 'промышленность'), ('6', 'торговля и коммерция'), ('7', 'строительство'), ('8', 'транспорт'), ('9', 'услуги'), ('10', 'прочие')], max_length=50)),
                ('average_income', models.IntegerField(verbose_name='средний доход')),
                ('id_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридическое лицо',
            },
            bases=('crm.client',),
        ),
    ]
