# Generated by Django 4.1.1 on 2022-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditspecialist',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты:'},
        ),
        migrations.AddField(
            model_name='occupation',
            name='name_job_title_add',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Добавить должность'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name_job_title',
            field=models.CharField(choices=[('CreditSpecialist', 'Кредитный специалист'), ('Creditadministrator', 'Кредитный администратор')], default='m', max_length=100, verbose_name='Наименование должности'),
        ),
    ]
