# Generated by Django 4.1.4 on 2022-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='statistics',
            field=models.TextField(blank=True, null=True, verbose_name='Предыдущие переговоры'),
        ),
    ]
