# Generated by Django 4.1.4 on 2023-01-29 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 29)),
        ),
    ]
