# Generated by Django 4.1.4 on 2023-02-01 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='id_credit_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кредитный специалист'),
        ),
        migrations.AddField(
            model_name='entity',
            name='id_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entity', to='crm.property', verbose_name='Залоговое имущество'),
        ),
        migrations.AddField(
            model_name='entity',
            name='souce_of_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.activity', verbose_name='Источник дохода'),
        ),
        migrations.AddField(
            model_name='datakk',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='ЧП/ИП'),
        ),
        migrations.AddField(
            model_name='datakk',
            name='id_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.entity', verbose_name='Юридическое лицо'),
        ),
        migrations.AddField(
            model_name='datakk',
            name='id_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кредитный спец'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='crm.client', verbose_name='ЧП/ИП'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='entity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='crm.entity', verbose_name='Юр.лицо'),
        ),
        migrations.AddField(
            model_name='company',
            name='field_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.activity', verbose_name='Cфера деятельности'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_credit_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кредитный специалист'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.guarantor', verbose_name='Поручитель'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Property', to='crm.property', verbose_name='Залоговое имущество'),
        ),
    ]
