# Generated by Django 4.1.4 on 2022-12-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='crm.client', verbose_name='ЧП/ИП'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='entity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='crm.entity', verbose_name='Юр.лицо'),
        ),
        migrations.AlterField(
            model_name='datakk',
            name='id_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='ЧП/ИП'),
        ),
        migrations.AlterField(
            model_name='datakk',
            name='id_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кредитный спец'),
        ),
    ]
