# Generated by Django 4.1.4 on 2022-12-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mortgaged_property',
        ),
    ]
