# Generated by Django 4.1.1 on 2022-10-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='crm.property', verbose_name='Залоговое имущество'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='time',
            field=models.CharField(max_length=30, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='datakk',
            name='id_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DataKK', to='crm.entity', verbose_name='Юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entity', to='crm.property', verbose_name='Залоговое имущество'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='company_images/%Y/%m/%', verbose_name='Фото'),
        ),
    ]
