# Generated by Django 4.1.1 on 2022-10-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_credit_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.specuser', verbose_name='Кредитный специалист'),
        ),
    ]
