# Generated by Django 4.1.1 on 2022-09-19 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_creditspecialist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activites', models.CharField(blank=True, choices=[('Сельское хозяйство', 'Сельское хозяйство'), ('торговля', 'торговля'), ('производство', 'производство')], max_length=100, null=True, verbose_name='Источник дохода')),
                ('activites_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Добавить источник дохода')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='company_files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name_job_title',
            field=models.CharField(blank=True, choices=[('CreditSpecialist', 'Кредитный специалист'), ('Creditadministrator', 'Кредитный администратор')], max_length=100, null=True, verbose_name='Наименование должности'),
        ),
        migrations.AlterField(
            model_name='company',
            name='field_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.activity', verbose_name='Cфера деятельности'),
        ),
    ]
