# Generated by Django 4.1.1 on 2022-09-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_activity_company_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Сфера деятельности'},
        ),
    ]
