# Generated by Django 4.1.4 on 2022-12-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_client_mortgaged_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='mortgaged_property',
        ),
    ]
