# Generated by Django 4.1.1 on 2022-10-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('crm', '0003_alter_client_id_credit_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datakk',
            name='id_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.specuser'),
        ),
    ]
