# Generated by Django 4.1.1 on 2022-10-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_id_credit_spec_alter_datakk_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.property', verbose_name='Залоговое имущество'),
        ),
        migrations.AlterField(
            model_name='images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crm.property'),
        ),
    ]
