# Generated by Django 4.1.4 on 2022-12-13 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_remove_entity_mortgaged_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='time',
        ),
        migrations.AlterField(
            model_name='client',
            name='id_guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.guarantor', verbose_name='Поручитель'),
        ),
        migrations.AlterField(
            model_name='client',
            name='monitoring_report',
            field=models.FileField(null=True, upload_to='media', verbose_name='Oтчет по мониторингу'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.CharField(max_length=8, unique=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='register_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Номер регистрации'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='datakk',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='ЧП/ИП'),
        ),
        migrations.AlterField(
            model_name='datakk',
            name='id_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.entity', verbose_name='Юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='datakk',
            name='id_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кредитный спец'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='court_documents',
            field=models.FileField(null=True, upload_to='Судебные документы/%Y/%m/%d', verbose_name='Судебные документы юр.лица'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id_credit_spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кредитный специалист'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='own_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Размер собвственного взноса'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='repaid_by_redemption',
            field=models.FileField(null=True, upload_to='Отступные документы/%Y/%m/%d', verbose_name='Отступные документы юр.лица'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='credit_history',
            field=models.FileField(null=True, upload_to='credit_history/%Y/%m/%d', verbose_name='Кредитная история'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='income_statement',
            field=models.FileField(null=True, upload_to='guarantor_income_statement/%Y/%m/%d', verbose_name='Справка о доходах'),
        ),
        migrations.AlterField(
            model_name='images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crm.property', verbose_name='Залоговое имущество'),
        ),
    ]
