# Generated by Django 4.1.4 on 2023-02-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_conversation_time_alter_client_id_guarantor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meet_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='crm.conversation', verbose_name='Переговоры'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='id_num_parley',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='crm.conversation', verbose_name='Переговоры'),
        ),
    ]
