# Generated by Django 4.1.4 on 2022-12-13 18:54

import crm.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_conversation_time_alter_client_id_guarantor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=crm.utils.CustomDateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время'),
        ),
    ]
