# Generated by Django 4.1.4 on 2022-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_conversation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время'),
        ),
    ]
